drop database if exists sqaproject;
create database sqaProject;
use sqaProject;
create table role(roleId int auto_increment primary key, roleName varchar(10) not null);
create table user(userId int auto_increment primary key, userName varchar(50) not null, userPassword varchar(15) not null, roleId int not null , userAge int not null, userEmail varchar(30) not null, userAddress varchar(50) not null, phoneNumber varchar(11) not null, foreign key(roleId) references role(roleId));
create table seatType(seatTypeId int auto_increment primary key, seatTypeName varchar(15) not null, seatTypeAmount int not null, price int not null);
create table bookedSeat(seatId int auto_increment primary key, seatName varchar(3), seatTypeId int not null, showTimeId int not null, foreign key(seatTypeId) references seatType(seatTypeId));
create table movie(movieId int auto_increment primary key, title varchar(100) not null, genre varchar(100), image text not null, trailerLink text not null, description text not null, length int not null, origin varchar(30), releasedDate date not null, director varchar(60), actors text);
create table showTime(showTimeId int auto_increment primary key, movieId int, startTime datetime not null, roomId int not null, foreign key(movieId) references movie(movieId));
create table ticket(userId int, seatId int, showTimeId int, foreign key(userId) references user(userId), foreign key(seatID)references bookedSeat(seatId), foreign key(showTimeId) references showTime(showTimeId));
create table food(foodId int auto_increment primary key, foodName varchar(30) not null, foodImage text, foodPrice int not null);
create table foodOrder(foodId int, userId int,amount int, foreign key(foodId)references food(foodId), foreign key(userId)references user(userId));
create table orderBill(userId int, orderDate DateTime, totalPrice int not null, paymentType varchar(20));

-- insert data

insert into role(roleName) values('admin'), ('normalUser');

insert into user(userName, userPassword, roleId, userAge, userEmail, userAddress, phoneNumber) values
	('admin', '123', 1, 23, 'admin@gmail.com', 'Hanoi', '0987654321'), 
	('quandd', '1234', 2, 31, 'quandd@gmail.com', 'Hanoi', '0917477321'), 
	('anonymous', 'hacker', 2, 33, 'hackeverything@gmail.com', 'russia', '0123456789'), 
	('noname', 'nopass', 1, 24, 'nothing@gmail.com', 'Hungyen', '0985647123'),
	('user', 'password', 2, 29, 'user@gamil.com', 'Thaibinh', '0223012431');

insert into seatType(seatTypeName, seatTypeAmount, price) values ('normal', '80', '100000'), ('vip', '20', '120000');

insert into food(foodName, foodImage,foodPrice) values ('popcorn', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ48HWW6R6Z8NfU7_pimnhzZpdSEWzkSbo1ZA&usqp=CAU', 50000), ('coca', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDhenlLq6nGz0a8z0dgMWc_MgdKX9iMH52gQ&usqp=CAU',30000), ('pepsi', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuE3lmhw3TBuWvmpELU97YPx6O5_81H8OUGA&usqp=CAU',30000),('snack', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVlIGlfeurCQb5KER-vlvmToi6iaiCci0-7g&usqp=CAU',10000);

insert into movie(title, genre, image, trailerLink, description, length, origin, releasedDate, director, actors) values 
	('TURNING RED: GẤU ĐỎ BIẾN HÌNH - P', 'Hoạt hình', 'https://chieuphimquocgia.com.vn/Content/Images/0016408_0.jpeg', 'https://www.youtube.com/watch?v=XdKzUbAiswE', '\'Turning Red - Gấu Đỏ Biến Hình\' từ Disney và Pixar kể về Mei Lee, cô bé 13 tuổi tự tin và ngổ ngáo với những sự hỗn loạn của tuổi mới lớn. Mẹ của Mei luôn cố gắng bảo bọc và ở bên cạnh con gái mọi lúc mọi nơi, khiến cô bé cảm thấy như một thảm hoạ vậy. Và cứ như thể những thay đổi về sở thích, các mối quan hệ và thể chất còn chưa đủ, mỗi khi Mei trở nên quá phấn khích (mà thật ra lúc nào cũng vậy), \'bùm\', cô bé sẽ biến hình thành một chú gấu đỏ siêu cute khổng lồ luôn!', 90, 'Mỹ', '2022/03/11', 'Domee Shi', 'Rosalie Chiang, Sandra Oh, James Hong'), 
    ('GÃ ĐIÊN BÁO THÙ - C18', 'Hành động', 'https://chieuphimquocgia.com.vn/Content/Images/0016424_0.jpeg', 'https://www.youtube.com/watch?v=j1g-sOkD9jU', 'Gã Điên Báo Thù xoay quanh H – tên thật là Patrick Hill (Jason Statham đóng), một nhân viên vừa được Fortico Securities thuê vào đội bảo an sau khi chiếc xe bọc thép chở đầy tiền của hãng hứng chịu một cuộc phục kích chết người. H là một kẻ trầm lặng, dường như gã coi công việc này chỉ là cần câu cơm kiếm sống qua ngày. Cho đến một ngày, chiếc xe tải mà H đang bảo vệ trở thành mục tiêu của một vụ cướp có chủ đích, những kỹ năng đáng gờm của gã được bộc lộ. Không chỉ là một tay thiện xạ, H còn là một kẻ không biết sợ, tàn nhẫn và máu lạnh. Sự thật nào ẩn giấu sau vẻ lãnh đạm của gã đàn ông cô độc song vô cùng nguy hiểm này?', 115, 'Mỹ', '2022-02-11', 'Guy Ritchie', 'Jason Statham, Holt McCallany, Jeffrey Donovan, Josh Hartnett, Scott Eastwood, Eddie Marsan'), 
    ('THE BATMAN - C16', 'Hành động, Hành động, Khoa học viễn tưởng, phiêu lưu', 'https://www.cgv.vn/media/catalog/product/cache/3/image/1800x/71252117777b696995f01934522c402d/t/h/the_batman_1_.jpg', 'https://www.youtube.com/watch?v=mqqft2x_Aa4', 'Bộ phim đưa khán giả dõi theo hành trình phá án và diệt trừ tội phạm của chàng Hiệp sĩ Bóng đêm Batman, với một câu chuyện hoàn toàn khác biệt với những phần phim đã ra mắt trước đây. Thế giới ngầm ở thành phố Gotham xuất hiện một tên tội phạm kỳ lạ tên Riddler chuyên nhắm vào nhân vật tai to mặt lớn. Và sau mỗi lần phạm tội, hắn đều để lại một câu đố bí ẩn cho Batman. Khi bắt tay vào phá giải các câu đố này, Batman dần lật mở những bí ẩn động trời giữa gia đình anh và tên trùm tội phạm Carmine Falcon', 170, 'Mỹ', '2022/03/04', 'Matt Reeves', 'Robert Pattinson, Zoë Kravitz, Paul Dano'), 
    ('NGƯỜI NHỆN KHÔNG CÒN NHÀ - C13', 'Hành động, Phiêu lưu', 'https://chieuphimquocgia.com.vn/Content/Images/0016369_0.jpeg', 'https://www.youtube.com/watch?v=JfVOs4VSpmA', 'Lần đầu tiên trong lịch sử điện ảnh của Người Nhện, thân phận người hàng xóm thân thiện bị lật mở, khiến trách nhiệm làm một Siêu Anh Hùng xung đột với cuộc sống bình thường và đặt người anh quan tâm nhất vào tình thế nguy hiểm. Khi anh nhờ đến giúp đỡ của Doctor Strange để khôi phục lại bí mật, phép thuật đã gây ra lỗ hổng thời không, giải phóng những ác nhân mạnh mẽ nhất từng đối đầu với Người Nhện từ mọi vũ trụ. Bây giờ, Peter sẽ phải vượt qua thử thách lớn nhất của mình, nó sẽ thay đổi không chỉ tương lai của chính anh mà còn là tương lai của cả Đa Vũ Trụ.', 135, 'Mỹ', '2021/12/17', 'Jon Watts', 'Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon, Jon Favreau'), 
    ('FAST & FURIOUS 9: HUYỀN THOẠI TỐC ĐỘ - C16', 'Hành động, Phiêu lưu', 'https://chieuphimquocgia.com.vn/Content/Images/0016368_0.jpeg', 'https://www.youtube.com/watch?v=FUK2kdPsBws', 'Hành động-mạo hiểm-kịch tính', 133, 'Mỹ', '2022-01-28', 'Justin Lin', 'Charlize Theron, Jim Parrack, John Cena'),
	('Bẫy ngọt ngào (2D) - C18', 'Tâm lý, tình cảm', 'https://chieuphimquocgia.com.vn/Content/Images/0015040_0.jpeg', 'https://www.youtube.com/watch?v=reyG2qWzG-M', 'Sau một thời gian dài không gặp, cuộc sống của mỗi thành viên trong hội ế đều có nhiều thay đổi. Camy là người duy nhất “thoát ế” với cuộc sống đáng mơ ước bên người chồng tài hoa Đăng Minh. Quỳnh Lam đã là một nhà thiết kế nổi tiếng, Linh Đan là một luật sư thành đạt, còn Ken trở thành ông chủ phòng gym. Cả nhóm quyết định hội ngộ nhân dịp kỷ niệm 3 năm ngày cưới của Camy. Từ đây, những góc khuất trong cuộc sống riêng của từng người dần được hé lộ. Hội ế sẽ làm gì khi phát hiện ra những bí mật của mỗi thành viên lại là nguyên nhân khiến tình bạn của họ đối mặt với sóng gió.', 90, 'Việt Nam', '2021-12-07', 'Đinh Hà Uyên Thư', 'Bảo Anh, Minh Hằng, Diệu Nhi, Thuận Nguyễn, Quốc Trường'),
	('SINH VẬT HUYỀN BÍ: NHỮNG BÍ MẬT CỦA DUMBLEDORE - C13', 'Phiêu lưu, Thần thoại', 'https://chieuphimquocgia.com.vn/Content/Images/0016419_0.jpeg', 'https://www.youtube.com/watch?v=DaM_wL1ZOM4', 'Câu chuyện của phần phim thứ ba này xoay quanh việc Giáo sư Albus Dumbledore (Jude Law) phát hiện ra việc Phù thủy Bóng tối quyền năng Gellert Grindelwald (Mads Mikkelsen) đang âm mưu chiếm lấy quyền kiểm soát Thế giới Phù thủy. Không thể một mình ngăn chặn đoàn quân hùng mạnh của của Grindelwald, Dumbledore đặt niềm tin vào Nhà nghiên cứu sinh vật huyền bí Newt Scamander (Eddie Redmayne) cùng đồng đội thực hiện nhiệm vụ đầy hiểm nguy này. Trong tình thế ngàn cân treo sợi tóc như vậy, liệu thầy Dumbledore có thể đứng ngoài được bao lâu?', 143, 'Mỹ', '2022/04/08', 'David Yates', 'Eddie Redmayne, Mads Mikkelsen, Ezra Miller, Katherine Waterston, Jude Law'),
	('ÁC MỘNG - C18', 'Kinh dị', 'https://chieuphimquocgia.com.vn/Content/Images/0016454_0.jpeg', 'https://www.youtube.com/watch?v=WOczM20igLw', 'Sau khi cố gắng tự lấy mạng sống của mình, một phụ nữ trẻ phải vật lộn với một người chồng “kỳ lạ”', 75, 'Mỹ', '2022/04/08', 'Adam Stilwell', 'Andrea Londo, Shawn Ashmore, Jane Badler'),
	('TIẾNG “KÊU” CỨU LÚC NỬA ĐÊM - c18', 'Tâm lý, tình cảm', 'https://chieuphimquocgia.com.vn/Content/Images/0016462_0.jpeg', 'https://www.youtube.com/watch?v=HM28wBN-5zc', 'Kyeong-mi là một cô gái khiếm thính làm việc tại một tổng đài hỗ trợ người khiếm thính. Một đêm đi làm về muộn, cô tình cờ chứng kiến So Jung-eun, một cô gái trẻ bị đâm tàn bạo trên con đường vắng. Từ giây phút đó, Kyeong-mi trở thành mục tiêu mới của kẻ sát nhân hai mặt Do-sik. Do-sik điên cuồng rượt đuổi cô gái khiếm thính để bịt đầu mối. Kyeong-mi, với bất lợi không nghe được bất kỳ âm thanh nào xung quanh, trở thành con mồi đáng thương trong cuộc rượt đuổi nghẹt thở này. Giữa cô gái khiếm thính và tên sát nhân điên loạn, cuộc rượt đuổi sẽ kết thúc như thế nào?', 103, 'Hàn Quốc', '2022/04/15', 'Kwon Oh-seung', 'Wi Ha-joon, Jin Ki-joo, Park Hoon, Kim Hye-yoon'),
	('ĐÊM TỐI RỰC RỠ - C18', 'Tầmz lý tình cảm', 'https://chieuphimquocgia.com.vn/Content/Images/0016456_0.jpeg', 'https://www.youtube.com/watch?v=ESx5SkBpiQ0', 'Khi người ông qua đời, cả gia đình của Xuân Thanh (Nhã Uyên) tề tựu để đưa tiễn. Đám tang diễn ra hoành tráng, xôm tụ và đầy màu sắc. Bỗng dưng một đám người kéo đến đòi nợ trong sự ngỡ ngàng của tất cả. Những bí mật bị phanh phui, bi kịch chồng bi kịch, như một hệ luỵ tổn thương của nạn bạo hành gia đình đầy ám ảnh.', 102, 'Việt Nam', '2022/04/08', 'Aaron Toronto', 'Kiến An, Phương Dung, Nhã Uyên, Xuân Trang, Diễm Phương, Kim B'),
	('QUA BỂN LÀM CHI - C16', 'Hài, Tâm lý, tình cảm', 'https://chieuphimquocgia.com.vn/Content/Images/0016437_0.jpeg', 'https://www.youtube.com/watch?v=XNqlFqIKeV0', 'Phim theo chân Tuấn (Thuận Nguyễn) – chàng sinh viên khoa tài chính điển trai đến Mỹ và sinh sống cùng chú Út (Quang Minh) của mình. Tại đây, anh đã gặp trợ lý của chú mình là Leo (Duy Khánh) - một anh chàng "say" anh như điếu đổ và có cuộc đụng độ đầy bất ngờ với Julie (Phương TiTi) ngay tại…phòng tắm! Một ngày, anh và Julie bất ngờ nhận được một đề nghị đầy cám dỗ từ Leo...và mọi việc bắt đầu rối tung lên theo một cách không ai lường trước được.', 90, 'Việt Nam', '2022/04/08', 'Nguyễn Trung Cang', 'Thuận Nguyễn, Quang Minh, Duy Khánh, Phương Titi, Peter Phạm'),
	('MORBIUS - C16', 'Hành động, Phiêu lưu', 'https://chieuphimquocgia.com.vn/Content/Images/0016443_0.png', 'https://www.youtube.com/watch?v=0vI-zC9dqDY', 'Một huyền thoại Marvel mới sắp lộ diện. Là ác nhân hay anh hùng? Sẽ phá hủy hay chữa lành thế giới này?', 98, 'Mỹ', '2022/04/01', 'Daniel Espinosa', 'Jared Leto, Michael Keaton, Adria Arjona'),
	('NHỮNG KẺ XẤU XA ( P-LT)', 'Hài, Hoạt hình', 'https://chieuphimquocgia.com.vn/Content/Images/0016416_0.jpeg', 'https://www.youtube.com/watch?v=m8Xt0yXaDPU', 'Hành trình trở thành người tốt đầy gay cấn và nhiều tiếng cười của băng đảng những loài thú xấu xa.', 95, 'Mỹ', '2022/03/25', 'Pierre Perifel', 'Sam Rockwell, Awkwafina, Anthony Ramos, Marc Maron');

-- insert into foodOrder(foodId, userId, amount) values (1, 2, 2), (2, 2, 3);

insert into bookedSeat(seatName, seatTypeId, showTimeId) values
																 ('A1', 1, 2),('A2', 1, 1),('A3', 1, 1),('A4', 1, 1),('A6', 1, 2),('A7', 1, 1),('A8', 1, 1),('A9', 1, 1),('A10', 1, 1),('B1', 1, 1),('B2', 1, 1),('B3', 1, 1),('B4', 1, 1),('B5', 1, 1),('B6', 1, 1),('B7', 1, 1),('B8', 1, 1),('B9', 1, 1),('B10', 1, 1),
																 ('C1', 1, 1),('C2', 1, 1),('C4', 1, 1),('C5', 1, 2),('C6', 1, 2),('C7', 1, 1),('C8', 1, 1),('C9', 1, 1),('C10', 1, 1),('D1', 1, 1),('D2', 1, 1),('D3', 1, 1),('D4', 1, 1),('D5', 1, 1),('D6', 1, 1),('D7', 1, 1),('D8', 1, 1),('D9', 1, 1),('D10', 1, 1),
																 ('E1', 1, 1),('E2', 1, 1),('E3', 1, 1),('E4', 1, 2),('E5', 1, 2),('E6', 1, 2),('E7', 1, 2),('E8', 1, 1),('E9', 1, 1),('E10', 1, 1),('F1', 1, 1),('F2', 1, 1),('F3', 1, 2),('F4', 1, 2),('F5', 1, 2),('F6', 1, 2),('F7', 1, 2),('F8', 1, 2),('F9', 1, 1),
																 ('G1', 1, 1),('G2', 1, 1),('G3', 1, 2),('G5', 1, 2),('G6', 1, 2),('G7', 1, 2),('G8', 1, 2),('G9', 1, 1),('G10', 1, 1),('H1', 1, 1),('H2', 1, 1),('H3', 1, 1),('H4', 1, 2),('H5', 1, 2),('H6', 1, 2),('H7', 1, 2),('H8', 1, 1),('H9', 1, 1),('H10', 1, 1),
																 ('I1', 1, 1),('I2', 1, 1),('I3', 1, 1),('I4', 1, 1),('I6', 1, 1),('I7', 1, 1),('I8', 1, 1),('I9', 1, 1),('I10', 1, 1),('J1', 1, 1),('J2', 1, 1),('J3', 1, 1),('J4', 1, 1),('J5', 1, 1),('J6', 1, 1),('J7', 1, 2),('J8', 1, 2),('J9', 1, 1),('J10', 1, 1),
																 ('G1', 1, 2),('G2', 1, 2),('G3', 1, 3),('G5', 1, 3),('G10', 1, 3),('A7', 1, 2),('G8', 1, 4),('G9', 1, 4),('G1', 1, 5),('H3', 1, 5),('H2', 1, 2),('H3', 1, 2),('H4', 1, 4),('H5', 1, 3),('H6', 1, 3),('H7', 1, 5),('H8', 1, 5),('H9', 1, 5),('H10', 1, 5),
																 ('I1', 1, 6),('I2', 1, 2),('I3', 1, 2),('I4', 1, 6),('I6', 1, 6),('I7', 1, 6),('I8', 1, 5),('I9', 1, 3),('I10', 1, 4),('J1', 1, 5),('J2', 1, 1),('J3', 1, 1),('J4', 1, 1),('J5', 1, 1),('J6', 1, 1),('J7', 1, 2),('J8', 1, 2),('J9', 1, 1),('J10', 1, 1);
																 
insert into showtime(movieId, startTime, roomId) values 
('1', '2022-04-15 09:00:00', '1'),
('2', '2022-04-15 11:30:00', '1'),
('3', '2022-04-15 14:00:00', '1'),
('4', '2022-04-15 16:30:00', '1'),
('2', '2022-04-15 09:00:00', '2'),
('5', '2022-04-15 11:30:00', '2'),
('4', '2022-04-15 14:00:00', '2'),
('1', '2022-04-15 16:30:00', '2');

commit;
 